### PR TITLE
Back port of 'Asynchronous requests to Tern Server (Issue #171)' into 0.8.x branch

### PR DESCRIPTION
**Pull request by vrubezhny**
Additional changes:
- refactoring of completion proposals collection - introduced a record
object to hold all information relevant to a completion item
- refactoring of collectors API - collection algorithms have been moved
out of *TernServer classes and placed in singletons

### CODE REVIEW

**Comment by vrubezhny** [comment]
@angelozerr, @pascalleclercq, Could you review the PR and (if it's OK) release AngularJS-Eclipse v.0.8.2 based on it?

What is done here:
* I've switched all the versions to 0.8.2-snapshot and used tern.java v.0.8.2 due to make it possible to build it (without doing this it was using tern.java 0.8.1 thus not giving a change to compile)
* cherry-picked the commit from @piotrtomiak 4a584b9daa0e7969e1e8fb9c4806c043ad72f3f5 (Asynchronous requests to Tern Server (Issue #171)) into the branch 0.8.x.

Thanks in advance!

**Comment by pascalleclercq** [comment]
Please find p2 repo : 

0.7.x branch release :
http://oss.opensagres.fr/tern.repository/0.7.1/
http://oss.opensagres.fr/angularjs-eclipse/0.7.1/

0.8.x branch release :
http://oss.opensagres.fr/tern.repository/0.8.2/
http://oss.opensagres.fr/angularjs-eclipse/0.8.2/

**Comment by angelozerr** [comment]
Thank a lot for your work @pascalleclercq !

@vrubezhny @alexeykazakov couldl you give us if it's OK for you?

**Comment by vrubezhny** [comment]
Unfortunately we had not to use v.0.7.2 in JBT 4.2.3 (There was a lot of changes so we couldn't fix this 'deadlock' issue), so we had to move to 0.8.2. And yes, it looks OK for us.

@angelozerr, @piotrtomiak and @pascalleclercq - thank you for your great work!

**Comment by angelozerr** [comment]
@vrubezhny  Glad of  the great work of @piotrtomiak and @pascalleclercq help and please you.

**Pull request merged**
