### PR TITLE
Asynchronous requests to Tern Server

### PR DESCRIPTION
**Pull request by piotrtomiak**
Changes required in AngularJS support for https://github.com/angelozerr/tern.java/pull/232

### CODE REVIEW

**Comment by angelozerr** [comment]
@piotrtomiak it seems that travis failed

**Comment by angelozerr** [comment]
It seems that's because tern was not updated.

**Comment by piotrtomiak** [comment]
> It seems that's because tern was not updated.

yeah, it should pass the build with changes merged in tern.java repo

**Comment by piotrtomiak** [comment]
Can you respin the build? It looks like it was using old version of tern.java.

**Pull request merged**
